### PR TITLE
base code structure

### PR DESCRIPTION
**Pull request by Dzarbis**
base code created

### CODE REVIEW

**Comment by Landonwilson1** [comment]
Looks good

**Review by isaac11195 — APPROVED** [review]
Nice job

**Review by Candyalexy1997 — COMMENTED** [review]
HTML looks good.
Missing files for js and css

**Review by Landonwilson1 — APPROVED** [review]
solid

**Review by Candyalexy1997 — APPROVED** [review]
Good to go!

**Pull request merged**
